### ISSUE TITLE
An error raised from cffi library when running via docker

### ISSUE THREAD

**Issue by hnykda** [jantman/python-wifi-survey-heatmap#11]
I am trying:

```
docker run -it --rm -p 5201:5201/tcp -p 5201:5201/udp jantman/python-wifi-survey-heatmap iperf3 -s
```

following with:
```
docker run \
               --net="host" \
               --privileged \
               --name survey \
               -it \
               --rm \
               -v (pwd):/pwd \
               -w /pwd \
               -e DISPLAY=$DISPLAY \
               -v "$HOME/.Xauthority:/root/.Xauthority:ro" \
               jantman/python-wifi-survey-heatmap \
               wifi-survey cwusbtplink 192.168.0.12 plan.png home
```

and when I click on the plan I get:

```
(wifi-survey:1): dbind-WARNING **: 20:56:31.608: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-0Cmc632T9B: No such file or directory
Traceback (most recent call last):
  File "/app/wifi_survey_heatmap/ui.py", line 239, in onLeftUp
    self._do_measurement(event.GetPosition())
  File "/app/wifi_survey_heatmap/ui.py", line 288, in _do_measurement
    iwc = self.collector.run_iwconfig()
  File "/app/wifi_survey_heatmap/collector.py", line 96, in run_iwconfig
    res = get_iwconfig(self._interface_name)
  File "/app/wifi_survey_heatmap/vendor/iwlib/iwconfig.py", line 30, in get_iwconfig
    return _get_iwconfig(interface, sock)
  File "/app/wifi_survey_heatmap/vendor/iwlib/iwconfig.py", line 98, in _get_iwconfig
    iwlib.iw_print_key(key, len(key), buf, key_size, flags)
AttributeError: cffi library 'wifi_survey_heatmap.vendor.iwlib._iwlib' has no function, constant or global variable named 'iw_print_key'
```

**Comment by jantman** [comment]
This should be fixed with 1.0.0 which was just released. Please feel free to re-open if it hasn't been.
